---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: false # No need of chef

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  ansible_verbosity: 2
  ansible_verbose: true
  require_ansible_omnibus: true
  require_chef_for_busser: false # No need of chef$
  #requirements_path: requirements-test.yml

platforms:
  - name: debian-wheezy
    driver_config:
      image: debian:wheezy-backports
      platform: debian

suites:
  - name: default
